APP_MAP = {
    "firefox": "firefox",
    "code": "code",
    "thunar": "thunar",
    "org.gnome.Nautilus": "nautilus",
    "chrome-chatgpt.com__-Default": "chromium -app=https://chat.openai.com",
    "chrome-keep.google.com__-Default": "chromium -app=https://keep.google.com",
    "chrome-drive.google.com__-Default": "chromium -app=https://drive.google.com",
    "chrome-web.whatsapp.com__-Default": "chromium -app=https://web.whatsapp.com",
    "chrome-github.com__-Default": "chromium -app=https://github.com",
    "chrome-youtube.com__-Default": "chromium -app=https://youtube.com",
    "chrome-www.udemy.com__home_my-courses_learning_-Default": "chromium -app=https://www.udemy.com/home/my-courses/learning/",
    "Spotify": "spotify",
    "Brave-browser": "brave-browser",
    "zen": "zen-browser",
    "obsidian": "obsidian",
    "org.gnome.Calculator": "gnome-calculator",
    "chromium": "chromium",
    "com.obsproject.Studio": "obs",
    "heroic": "heroic",
    "libreoffice-writer": "libreoffice",
    "libreoffice": "libreoffice",
}
